name:  Publish-Crate-Automatically
on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish-Automatically
    runs-on: ubuntu-latest
    steps:
	- name: publish crates
	  uses: katyo/publish-crates@v1

#        uses: actions/checkout@v2
#        uses: actions-rs/toolchain@v1
#        with:
#          toolchain: stable
#          override: true
#	uses: katyo/publish-crates@v1
#	with:
#	    registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
