name: Publish-Crate-Upon-Release
on:
  release:
    types: [published]

jobs:
  publish-automatically:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v2
      -  uses: actions-rs/toolchain@v1
         with:
           toolchain: stable
           override: true

      - name: publish crates
        uses: katyo/publish-crates@v1
        with: 
          registry-token: cioDgP0Dnd6d81kixn75NBoFQz02UzBsKpu